init:
  - appveyor version
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
  - sh: lsb_release -d

services:
  - docker

test_script:
  - docker run hello-world
  - docker build -t friendlyhello .
  - docker images
  - docker system df

build: off
