init:
  - appveyor version
  - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
  - sh: lsb_release -d
  #- sh: cat /etc/modules-load.d/modules.conf
  #- sh: ls /etc/modules-load.d
  #- sh: ls -al /etc/modprobe.d
  #- sh: lsmod
  
services:
  - docker

test_script:
  - docker version
  - sh: |
      DOCKER_INFO = $(docker info)
      echo $DOCKER_INFO | grep -q 'Native Overlay Diff: true' && echo 'matched'
  - docker run hello-world
  - docker build -t friendlyhello .
  - docker images
  - docker system df

build: off
